name: Build PCem

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-3-dev libglew-dev libsdl2-dev libopenal-dev libwxgtk3.0-dev
      - name: Configure
        run: ./configure --enable-release
      - name: Build
        run: make -j$(nproc)
